### ISSUE TITLE
Add reviewers names in post meta ?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#486]
Each reviewers can add a commit in order to add himself in the post reviewers list metadata (eg: after authors). Reviewing a post is a contribution imo.
What do you think ?

**Comment by lionelB** [comment]
it's a good idea :+1:

**Comment by Nyalab** [comment]
it would promote reviewing posts, so it's a good idea (it cannot be automated right ? because of squashes, didn't it?)

**Comment by madx** [comment]
:+1: for me as well

**Comment by Macxim** [comment]
Completely agree.

**Comment by magsout** [comment]
agree

**Comment by Nyalab** [comment]
so, we all agree, let's just say that when we post something, it does not have to be a unique commit, we will now squash cleverly to let people that have contributed to the writing of the post in the history

**Comment by MoOx** [comment]
No I mean, we should add them. A reviewer can not push any commit.

**Comment by Nyalab** [comment]
i don't know how we can exactly handle this to mirror the reality but if we can display on the post all people that have commited or talked in the PR but that will not enhance the reviewer importance compared to the guy that just talks in the PR

**Comment by MoOx** [comment]
> i don't know how we can exactly handle this to mirror the reality

By hand, like the "authors" field.

**Comment by MoOx** [comment]
The author(s) add themselves the reviewer names.

**Comment by Nyalab** [comment]
oh! by hand! ok! just let's put them in a `reviewers` field, the author has the be the star of the post :stuck_out_tongue:

**Comment by Nyalab** [comment]
Ok, so, i began to work on it, wanting to replace everything in each post with a `reviewers` field, but that is not really what we want. Today, the problem is that someone who talks on a PR helping the author will never be displayed as a contributor although the one that "just" fixes a mistake with the "edit" link on the post page will.

So i decided to keep the contributors like it is right now, and just merge with it the reviewers field.

Just look at #635 and you will understand.
