### ISSUE TITLE
Post : CSS Tooling evolution

### ISSUE THREAD

**Issue by thibthib** [putaindecode/putaindecode.io#616]
Originally I wanted to write an article for my fellow back-end developers here at my company about how the CSS writing and tooling evolved in the last few years, with the aim to present in the end the [CSS Modules](https://github.com/css-modules/css-modules).
As I started thinking about it, and taking into account that my public is really novice about CSS and its issues, I realized I needed to first explain what the main issue with CSS was (the global scope with the cascade), and how with tooling we work around it.
I already wrote a [draft on Medium](https://medium.com/@thib_thib/d2dfc17a6fcd) explaining first how the cascade works (quickly), and then how I used tooling in my past experience to make my life easier : first I used pre-processors, then Methodologies like BEM, and finally CSS Modules.

I don't know if this article fits well into putaindecode as the public may not be the same, but I could maybe remove the first cascade explaining part, or at least split it in two parts.

What do you think ?

**Comment by MoOx** [comment]
Looks good. One rule we got is that a post must be at least in french. Are you open to made the translation by youself (since you are french)? If so, we might add some links to existing content when relevant. Example:

- http://putaindecode.io/fr/articles/css/bem/maintenance-evolutivite/
- http://putaindecode.io/fr/articles/css/bem/
- http://putaindecode.io/fr/articles/css/preprocesseurs/

 And maybe some others.

Anyway, this post is a good idea.

Feel free to make a PR. CONTRIBUTING.md should help for now (this need to be updated, but currently there is not a lot of contributor and I am personnally busy with some other open sources project). You can ask more help here (or on Discord for live support - see Discuss link in website header) if needed.

**Comment by thibthib** [comment]
Yeah sure, I can translate in french 🇫🇷
I'll make the PR and add the links ! Thanks.

**Comment by MoOx** [comment]
Published already.
